### ISSUE TITLE
Helping to reduce cost of DDoS on comparisons

### ISSUE THREAD

**Issue by jtlapp** [hapijs/cryptiles#20]
To help callers limit the cost of DDoS attacks, it might be useful to rename the ``a`` and ``b`` parameters of fixedTimeComparison(). The ``b = a`` assignment performs a comparison over the length of ``a`` when ``a`` and ``b`` disagree in length. If the attacker is providing ``a``, the attacker can make the server work harder by providing excessively long values.

Mind you, bitwise OR operations aren't all that expensive, but if a caller can be empowered to reduce the impact of DDoS attacks by even a little, it seems like it would be useful to do so.

Renaming ``a`` to ``validMac`` and ``b`` to ``testMac`` should suffice.

(Also, I'm not sure I see the value of keeping the attacker blind to digest length. If the digest isn't strong enough at its valid length, it's too short. Another way to eliminate the DDoS cost is to quit the comparison immediately upon determining that the strings have different lengths.)

**Comment by jtlapp** [comment]
Short-circuting the comparison on different lengths also has the benefit of eliminating this DDoS issue for everyone without anyone having to swap fixedTimeComparison() parameters.

**Comment by hueniverse** [comment]
I don't see how this is worth spending time on.
