### ISSUE TITLE
Use crypto.timingSafeEqual for fixedTimeComparison

### ISSUE THREAD

**Issue by ChALkeR** [hapijs/cryptiles#24]
Node.js 6.6.0 has [crypto.timingSafeEqual()](https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b), which operates on two `Buffer`s of the same length.

You should probably use it instead of a [js-land magic](https://github.com/hapijs/cryptiles/blob/master/lib/index.js#L81-L85) to securely compare digests.

See https://github.com/nodejs/node/pull/8304 and https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.6.0.

**Comment by hueniverse** [comment]
I will as soon as hapi doesn't support any other version of node. I'll leave this open as a reminder.

**Comment by ChALkeR** [comment]
@hueniverse You could use a simple feature detection (i.e. `if (crypto.timingSafeEqual) {`).

**Comment by hueniverse** [comment]
I don't like doing that. Makes it harder to reason about code across platforms.
