### ISSUE TITLE
fixedTimeComparison(<String> a, <String> b)  is removed?

### ISSUE THREAD

**Issue by malinda89** [hapijs/cryptiles#29]
Has the **fixedTimeComparison** function been removed? If so can you please update the README as well. Please suggest any alternatives for this function.

**Comment by Marsup** [comment]
I think https://github.com/hapijs/cryptiles/issues/24 first suggested to get rid of it, with the alternative.

**Comment by hueniverse** [comment]
https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_crypto_timingsafeequal_a_b
