### ISSUE TITLE
fixedTimeComparison function missing

### ISSUE THREAD

**Issue by raj-krrish** [hapijs/cryptiles#30]
[NPM](https://www.npmjs.com/package/cryptiles) page says it has fixedTimeComparison function. But I can't see that function.

**Comment by mtharrison** [comment]
It has been removed in favour of using the built in one in node crypto module (https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b).

**Comment by Marsup** [comment]
Github shows the master branch.
