### ISSUE TITLE
Node version requirement incompatible with v18.4.1 of hapi

### ISSUE THREAD

**Issue by rossanthony** [hapijs/cryptiles#52]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): not yet

#### Context

* *node version*: 10
* *module version*: n/a
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): used with Hapi v18.4.1
* *any other relevant information*: 

#### How can we help?

When doing an npm install we are seeing the follow error:

_@hapi/cryptiles@5.1.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.16.0"_

We are not using cryptiles in our project directly, it seems to be coming in as a subdependency of something that hapi indirectly relies on...

@hapi/hapi > @hapi/statehood > @hapi/iron > @hapi/cryptiles

So while hapi v18 is compatible with node >=10, its sub-dependencies are requiring at least node v12.

It was introduced in this commit: https://github.com/hapijs/cryptiles/commit/7ee1963d0a6cf44bdb7bf2ec73d56a3eebff4c03#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R9 where the following was added to the package.json of cryptiles:
```
"engines": {
    "node": ">=12.0.0"
},

**Comment by hueniverse** [comment]
hapi 18 uses version 4 of this module.
